# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 146b411db92206e05af4c02dcb0ac77db0925dff83ca4ecef8434aa8b8ed381203ae3c4cd809d684ec9a9108054b0a1621b9f409c6babf904e0f876a129f56c8
  devise_secret_key: 2cb5fde01129a9598d708352b78d62b5a7a7ac96de19776e1b963b9a6b727684539aae763b59ed84c5ea7e3e62a05a35da97c817cc79e8bcf605d6364b27d220
  orcid_key: <%= ENV["ORCID_KEY"] %>
  orcid_secret: <%= ENV["ORCID_SECRET"] %>
  paperclip_hash_secret: 4870e92d15e0f602e25751fe51f18c9a05fac2bda7520a4ed73a0885fc96e19621df3aacbeab2edef319be3247d41c6ec10b98d79e9d93ea7f729bc0d7aea380

test:
  secret_key_base: dc681d4add36415b18f7b6b4437622f306beee43009105c8ddc98ca88729a939d866bbc78923b454749f9999b4df07ad6d71c566395cb38f4c1179ff6965b31b
  devise_secret_key: b5b4d61cbb62a63cd2d5f3ef7c22811a5d54ba8f51a9ad9e1a790368e73f3d2244d72ed3d0e777cf9cbce3372ffb9694896dbbd5152709979aa5779031ba914e
  orcid_key: <%= ENV["ORCID_KEY"] %>
  orcid_secret: <%= ENV["ORCID_SECRET"] %>
  paperclip_hash_secret: b86330aeef94b2c1b642e64f70807cac22830bc9553d82164e7bde03c03fc4743a651680a8a200fefe915684aacf1f28270a5ad680f41718358defe5e253740c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY_BASE"] %>
  orcid_key: <%= ENV["ORCID_KEY"] %>
  orcid_secret: <%= ENV["ORCID_SECRET"] %>
  paperclip_hash_secret: <%= ENV["PAPERCLIP_HASH_SECRET"] %>
