development:
  zenodo_server: https://sandbox.zenodo.org/

test:
  zenodo_server: https://sandbox.zenodo.org/

production:
  zenodo_server: https://sandbox.zenodo.org/
#  zenodo_server: https://zenodo.org/
